openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API for managing products
  contact:
    name: PaytonKawa
    email: 
servers:
  - url: http://localhost:3001

components:
  schemas:
    Product:
      type: object
      required:
        - createdAt
        - name
        - details
        - stock
      properties:
        createdAt:
          type: string
          format: date
        name:
          type: string
        details:
          type: object
          properties:
            price:
              type: string
            description:
              type: string
            color:
              type: string
        stock:
          type: integer

paths:
  /product:
    post:
      summary: Create a new product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: The product was successfully created
        '400':
          description: Bad request

  /products:
    get:
      summary: Get all products
      tags:
        - Product
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /product/{id}:
    get:
      summary: Get a product by ID
      tags:
        - Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The product ID
      responses:
        '200':
          description: The product description by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

    put:
      summary: Update a product by ID
      tags:
        - Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: The product was updated
        '404':
          description: Product not found

    delete:
      summary: Delete a product by ID
      tags:
        - Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The product ID
      responses:
        '200':
          description: The product was deleted
        '404':
          description: Product not found
